name: flutter_html
description: A Flutter widget for rendering static HTML and CSS as Flutter widgets.
version: 3.0.0-beta6787
homepage: https://github.com/Sub6Resources/flutter_html

environment:
  sdk: '>=3.0.0'
  flutter: ^3.29.3

dependencies:
  # Plugin for parsing html
  html: ^0.15.3

  # Plugin for parsing css
  csslib: ^0.17.2

  # Plugin for firstWhereOrNull extension on lists
  collection: ^1.17.0

  # plugin to manage lists and counting in a variety of styles
  list_counter: ^1.0.2
  flutter_layout_grid: '>=1.0.1 <3.0.0'

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  meta: ^1.8.0
  melos: ^3.0.1

funding:
  - https://opencollective.com/flutter_html

topics:
  - html
  - css
  - widgets
  - layout
  - flutter-html
